language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t vbh18kas/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true vbh18kas/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-react"
    env: "Docker-env"
    bucket_name: ""
    bucket_path: "docker-react"
    on:
        branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY